### ISSUE TITLE
Hamburger menu only changing view when words are clicked

### ISSUE THREAD

**Issue by 3xFail** [huffSamuel/MobileHotkey-Issues#5]
- [ ] Client
- [X] Server

Version: 1.1

### Summary
Hamburger menu only changes view if words themselves are clicked on just the area of the words 

### Expected behavior
I would expect when clicking the area for the menu option that it would take me to the view for that option
### Actual behavior
It closes the menu and stays on the current page
### Steps to reproduce
Open hamburger menu
Click in the area for settings (except for the word)
Watch menu close and view not update
### Log files
Not sure which log file is wanted.

**Comment by huffSamuel** [comment]
Unable to replicate. Log files are in INSTALL_DIR\logs\MobileHotkey.log but will not include data to this level yet.

![issue 5](https://user-images.githubusercontent.com/17741817/39100061-d5d97efa-4638-11e8-94fa-b70299e02fee.gif)

**Comment by huffSamuel** [comment]
Version 0.1.2 onward have an optimized navigation control that will not suffer from this in any way. Closing ticket.
